services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  JBartels\BeAcl\:
    resource: '../Classes/*'

  JBartels\BeAcl\Controller\PermissionController:
    tags: ['backend.controller']
